brendan_test:
  target: dev
  outputs:
    dev:
      type: databricks
      host: 127.0.0.1
      token: <YOUR_REAL_TOKEN>
      http_path: <YOUR_REAL_HTTP_PATH>
      catalog: hive_metastore
      schema: dbt_scratch
      threads: 1